### ISSUE TITLE
Syntax error in source code

### ISSUE THREAD

**Issue by dfkettle** [MostAwesomeDude/continued#1]
After installing, I get this error on the import statement:

```
import continued
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\continued.py", line 304
    raise ValueError, "Can't normalize infinite continued fractions!"
                    ^
SyntaxError: invalid syntax
```

I'm running Python 3.10.9 (under Thonny 4.0.2) on Windows 10.

**Comment by MostAwesomeDude** [comment]
This isn't a Python 3 package, but a Python 2.7 package.

**Comment by dfkettle** [comment]
Any plans to update it for Python 3?

**Comment by MostAwesomeDude** [comment]
Not really. I encourage you to read the code, read the various papers, try to make sense of Gosper's diagrams, and get your own intuition for how continued fractions work. Then, try to write your own Gosper-machine implementation.

There's two problems with trying to use this code for anything serious. The first problem is that the Cauchy convergents are just not very good. For Hurwitz numbers (`e` and friends) they're fine, and I bet that they're also acceptable for surds (square roots, etc.) but they don't obey any sort of fast Cauchy convergence property. I didn't know that this was a thing when I wrote this code!

The second problem is that e.g. `sqrt(8) * sqrt(8)` diverges; the computed coefficients are [8; 0, 0, ..]. This is tricky to overcome; the Gosper machine needs to not just propagate infinity, but propagate information about zero-ness or infinite-ness at each extremal point.
